// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"conduit/app/article/service/internal/biz"
	"conduit/app/article/service/internal/data"
	"conduit/app/article/service/internal/server"
	"conduit/app/article/service/internal/service"
	"conduit/pkg/client"
	"conduit/pkg/conf"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	discovery := data.NewDiscovery(confData, logger)
	userClient := client.NewUserServiceClient(discovery)
	dataData, cleanup, err := data.NewData(logger, db, userClient)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo, logger)
	articleService := service.NewArticleService(articleUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, articleService, logger)
	grpcServer := server.NewGRPCServer(confServer, articleService, logger)
	registrar := data.NewRegistrar(confData, logger)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
