apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conduit-article-dep
  name: conduit-article-dep
  namespace: conduit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduit-article-dep
  template:
    metadata:
      labels:
        app: conduit-article-dep
    spec:
      containers:
        - name: conduit-article
          image: "ccr.ccs.tencentyun.com/conduit/conduit-article:1.0.4"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort:  9002
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi