// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package interfacePb

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 422
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsContentMissing(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CONTENT_MISSING.String() && e.Code == 422
}

func ErrorContentMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_CONTENT_MISSING.String(), fmt.Sprintf(format, args...))
}

func IsParamIllegal(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PARAM_ILLEGAL.String() && e.Code == 422
}

func ErrorParamIllegal(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_PARAM_ILLEGAL.String(), fmt.Sprintf(format, args...))
}
