article_service:
  server:
    grpc:
      addr: 0.0.0.0:9000
      timeout: 1s
user_service:
  server:
    grpc:
      addr: 0.0.0.0:9001
      timeout: 1s
conduit_interface:
  server:
    http:
      addr: 0.0.0.0:8000
      timeout: 1s
data:
  database:
    driver: mysql
    source: wangzhe:qwe254511@tcp(119.91.235.156:3306)/conduit?charset=utf8mb4&parseTime=True&loc=Local
    max_idle_connections: 100
    max_open_connections: 100
    max_connection_life_time: 10
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  etcd:
    addr: ['127.0.0.1:2379']
biz:
  jwt_secret: secret
