apiVersion: v1
kind: Pod
metadata:
  name: conduit-user-manual-md
  labels:
      create_method: manual
spec:
  containers:
    - name: conduit-user-manual
      image: registry.cn-shenzhen.aliyuncs.com/wangzhe0568/conduit-user:1.0.1
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
  imagePullSecrets:
    - name: regsecret